/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Cadastro.Cliente_Mensalista;
import Cadastro.Entrada_Veiculo;
import Cadastro.Saida_Veiculo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Higor
 */
public class NewSystem_Gerente extends javax.swing.JFrame {

    /**
     * Creates new form NewSystem_Gerente
     */
    public NewSystem_Gerente() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBEntrada = new javax.swing.JButton();
        jBSaida = new javax.swing.JButton();
        jBCaixa = new javax.swing.JButton();
        jBCliente = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ClienteMensalista_ = new javax.swing.JMenuItem();
        Funcionario_ = new javax.swing.JMenuItem();
        Gerente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        EntradaVeiculo_ = new javax.swing.JMenuItem();
        SaidaVeiculo_ = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ConsultarClienteMensalista_ = new javax.swing.JMenuItem();
        ConsultarFuncionario = new javax.swing.JMenuItem();
        ConsultarGerente = new javax.swing.JMenuItem();
        ConsultarLogin_ = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        RelatorioMensal_ = new javax.swing.JMenuItem();
        RelatorioAvulso_ = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        AbrirCalc = new javax.swing.JMenuItem();
        AbrirBlocoNotas_ = new javax.swing.JMenuItem();
        MenuSAIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NewSystem - Gerente");

        jBEntrada.setText("Entra V");
        jBEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntradaActionPerformed(evt);
            }
        });

        jBSaida.setText("Saida V");
        jBSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaidaActionPerformed(evt);
            }
        });

        jBCaixa.setText("Caixa");
        jBCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCaixaActionPerformed(evt);
            }
        });

        jBCliente.setText("Add  Cliente");
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Cadastrar");

        ClienteMensalista_.setText("Cliente Mensalista");
        ClienteMensalista_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteMensalista_ActionPerformed(evt);
            }
        });
        jMenu1.add(ClienteMensalista_);

        Funcionario_.setText("Funcionário");
        Funcionario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Funcionario_ActionPerformed(evt);
            }
        });
        jMenu1.add(Funcionario_);

        Gerente.setText("Gerente");
        Gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenteActionPerformed(evt);
            }
        });
        jMenu1.add(Gerente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lançamentos");

        EntradaVeiculo_.setText("Entrada de Veiculo");
        EntradaVeiculo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaVeiculo_ActionPerformed(evt);
            }
        });
        jMenu2.add(EntradaVeiculo_);

        SaidaVeiculo_.setText("Saída de Veiculo");
        SaidaVeiculo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaVeiculo_ActionPerformed(evt);
            }
        });
        jMenu2.add(SaidaVeiculo_);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultar");

        ConsultarClienteMensalista_.setText("Cliente Mensalista");
        ConsultarClienteMensalista_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClienteMensalista_ActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarClienteMensalista_);

        ConsultarFuncionario.setText("Funcionário");
        ConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarFuncionario);

        ConsultarGerente.setText("Gerente");
        ConsultarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarGerenteActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarGerente);

        ConsultarLogin_.setText("Login");
        ConsultarLogin_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarLogin_ActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarLogin_);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Relatório");

        RelatorioMensal_.setText("Mensal");
        RelatorioMensal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioMensal_ActionPerformed(evt);
            }
        });
        jMenu6.add(RelatorioMensal_);

        RelatorioAvulso_.setText("Avulso");
        RelatorioAvulso_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioAvulso_ActionPerformed(evt);
            }
        });
        jMenu6.add(RelatorioAvulso_);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Ferramentas");

        AbrirCalc.setText("Calculadora");
        AbrirCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCalcActionPerformed(evt);
            }
        });
        jMenu5.add(AbrirCalc);

        AbrirBlocoNotas_.setText("Bloco de Notas");
        AbrirBlocoNotas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBlocoNotas_ActionPerformed(evt);
            }
        });
        jMenu5.add(AbrirBlocoNotas_);

        jMenuBar1.add(jMenu5);

        MenuSAIR.setText("Sair");
        MenuSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSAIRActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuSAIR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(795, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntradaActionPerformed
        Entrada_Veiculo e = new Entrada_Veiculo(null,true);
        e.setVisible(true);
    }//GEN-LAST:event_jBEntradaActionPerformed

    private void jBSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaidaActionPerformed
      Saida_Veiculo s = new Saida_Veiculo(null,true);
      s.setVisible(true);
    }//GEN-LAST:event_jBSaidaActionPerformed

    private void jBCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCaixaActionPerformed
        Caixa.Caixa_Mensalista c = new  Caixa.Caixa_Mensalista (null,true);
        c.setVisible(true);     
    }//GEN-LAST:event_jBCaixaActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        Cliente_Mensalista c = new Cliente_Mensalista(null,true);
        c.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void RelatorioMensal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioMensal_ActionPerformed
        Relatorio.Relatorio_ClienteMensalista c = new  Relatorio.Relatorio_ClienteMensalista(null,true);
        c.setVisible(true);
    }//GEN-LAST:event_RelatorioMensal_ActionPerformed

    private void ClienteMensalista_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteMensalista_ActionPerformed
         Cliente_Mensalista c = new Cliente_Mensalista(null,true);
        c.setVisible(true);
    }//GEN-LAST:event_ClienteMensalista_ActionPerformed

    private void Funcionario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Funcionario_ActionPerformed
         Cadastro.Funcionario c = new Cadastro.Funcionario(null,true);
        c.setVisible(true);
    }//GEN-LAST:event_Funcionario_ActionPerformed

    private void GerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenteActionPerformed
         Cadastro.Gerente c = new  Cadastro.Gerente(null,true);
         c.setVisible(true);
    }//GEN-LAST:event_GerenteActionPerformed

    private void EntradaVeiculo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaVeiculo_ActionPerformed
       Cadastro.Entrada_Veiculo c = new  Cadastro.Entrada_Veiculo (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_EntradaVeiculo_ActionPerformed

    private void SaidaVeiculo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaVeiculo_ActionPerformed
      Cadastro.Saida_Veiculo c = new  Cadastro.Saida_Veiculo (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_SaidaVeiculo_ActionPerformed

    private void ConsultarClienteMensalista_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClienteMensalista_ActionPerformed
        Pesquisa.Cliente_Mensalista c = new  Pesquisa.Cliente_Mensalista (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_ConsultarClienteMensalista_ActionPerformed

    private void ConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFuncionarioActionPerformed
        Pesquisa.Funcionario c = new   Pesquisa.Funcionario  (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_ConsultarFuncionarioActionPerformed

    private void ConsultarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarGerenteActionPerformed
     Pesquisa.Pesquisar_Gerente c = new   Pesquisa.Pesquisar_Gerente  (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_ConsultarGerenteActionPerformed

    private void ConsultarLogin_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarLogin_ActionPerformed
        Pesquisa.Login c = new   Pesquisa.Login (null,true);
         c.setVisible(true);
    }//GEN-LAST:event_ConsultarLogin_ActionPerformed

    private void RelatorioAvulso_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioAvulso_ActionPerformed
      Relatorio.Relatorio_Cliente c = new  Relatorio.Relatorio_Cliente(null,true);
        c.setVisible(true);
    }//GEN-LAST:event_RelatorioAvulso_ActionPerformed

    private void AbrirCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCalcActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            JOptionPane.showInputDialog("",ex);
        }
    }//GEN-LAST:event_AbrirCalcActionPerformed

    private void AbrirBlocoNotas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBlocoNotas_ActionPerformed
        try {
            Runtime.getRuntime().exec("notepad");
        } catch (IOException ex) {
            JOptionPane.showInputDialog("",ex);
        }
    }//GEN-LAST:event_AbrirBlocoNotas_ActionPerformed

    private void MenuSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSAIRActionPerformed
          System.exit(0);
    }//GEN-LAST:event_MenuSAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSystem_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSystem_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSystem_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSystem_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSystem_Gerente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirBlocoNotas_;
    private javax.swing.JMenuItem AbrirCalc;
    private javax.swing.JMenuItem ClienteMensalista_;
    private javax.swing.JMenuItem ConsultarClienteMensalista_;
    private javax.swing.JMenuItem ConsultarFuncionario;
    private javax.swing.JMenuItem ConsultarGerente;
    private javax.swing.JMenuItem ConsultarLogin_;
    private javax.swing.JMenuItem EntradaVeiculo_;
    private javax.swing.JMenuItem Funcionario_;
    private javax.swing.JMenuItem Gerente;
    private javax.swing.JMenu MenuSAIR;
    private javax.swing.JMenuItem RelatorioAvulso_;
    private javax.swing.JMenuItem RelatorioMensal_;
    private javax.swing.JMenuItem SaidaVeiculo_;
    private javax.swing.JButton jBCaixa;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBEntrada;
    private javax.swing.JButton jBSaida;
    private javax.swing.JButton jBSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
